// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/pbufio/pbuf-registry/internal/model"

	uuid "github.com/google/uuid"
)

// ACLRepository is an autogenerated mock type for the ACLRepository type
type ACLRepository struct {
	mock.Mock
}

// CheckPermission provides a mock function with given fields: ctx, userID, moduleName, permission
func (_m *ACLRepository) CheckPermission(ctx context.Context, userID uuid.UUID, moduleName string, permission model.Permission) (bool, error) {
	ret := _m.Called(ctx, userID, moduleName, permission)

	if len(ret) == 0 {
		panic("no return value specified for CheckPermission")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, model.Permission) (bool, error)); ok {
		return rf(ctx, userID, moduleName, permission)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, model.Permission) bool); ok {
		r0 = rf(ctx, userID, moduleName, permission)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, model.Permission) error); ok {
		r1 = rf(ctx, userID, moduleName, permission)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserPermissions provides a mock function with given fields: ctx, userID
func (_m *ACLRepository) DeleteUserPermissions(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPermissions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GrantPermission provides a mock function with given fields: ctx, entry
func (_m *ACLRepository) GrantPermission(ctx context.Context, entry *model.ACLEntry) error {
	ret := _m.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for GrantPermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.ACLEntry) error); ok {
		r0 = rf(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListUserPermissions provides a mock function with given fields: ctx, userID
func (_m *ACLRepository) ListUserPermissions(ctx context.Context, userID uuid.UUID) ([]*model.ACLEntry, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPermissions")
	}

	var r0 []*model.ACLEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.ACLEntry, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.ACLEntry); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ACLEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RevokePermission provides a mock function with given fields: ctx, userID, moduleName
func (_m *ACLRepository) RevokePermission(ctx context.Context, userID uuid.UUID, moduleName string) error {
	ret := _m.Called(ctx, userID, moduleName)

	if len(ret) == 0 {
		panic("no return value specified for RevokePermission")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, userID, moduleName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewACLRepository creates a new instance of ACLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewACLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ACLRepository {
	mock := &ACLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
