// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CompactionDaemon is an autogenerated mock type for the CompactionDaemon type
type CompactionDaemon struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *CompactionDaemon) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCompactionDaemon creates a new instance of CompactionDaemon. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompactionDaemon(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompactionDaemon {
	mock := &CompactionDaemon{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
