// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/pbufio/pbuf-registry/internal/model"
)

// DriftRepository is an autogenerated mock type for the DriftRepository type
type DriftRepository struct {
	mock.Mock
}

// AcknowledgeDriftEvent provides a mock function with given fields: ctx, eventID, acknowledgedBy
func (_m *DriftRepository) AcknowledgeDriftEvent(ctx context.Context, eventID string, acknowledgedBy string) error {
	ret := _m.Called(ctx, eventID, acknowledgedBy)

	if len(ret) == 0 {
		panic("no return value specified for AcknowledgeDriftEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, eventID, acknowledgedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ComputeAndStoreHashes provides a mock function with given fields: ctx, tagID
func (_m *DriftRepository) ComputeAndStoreHashes(ctx context.Context, tagID string) error {
	ret := _m.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for ComputeAndStoreHashes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tagID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDriftEventsForModule provides a mock function with given fields: ctx, moduleID
func (_m *DriftRepository) GetDriftEventsForModule(ctx context.Context, moduleID string) ([]model.DriftEvent, error) {
	ret := _m.Called(ctx, moduleID)

	if len(ret) == 0 {
		panic("no return value specified for GetDriftEventsForModule")
	}

	var r0 []model.DriftEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.DriftEvent, error)); ok {
		return rf(ctx, moduleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.DriftEvent); ok {
		r0 = rf(ctx, moduleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DriftEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, moduleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFileHashesForTag provides a mock function with given fields: ctx, tagID
func (_m *DriftRepository) GetFileHashesForTag(ctx context.Context, tagID string) (map[string]string, error) {
	ret := _m.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for GetFileHashesForTag")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, tagID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, tagID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPreviousTagID provides a mock function with given fields: ctx, moduleID, currentTagID
func (_m *DriftRepository) GetPreviousTagID(ctx context.Context, moduleID string, currentTagID string) (string, error) {
	ret := _m.Called(ctx, moduleID, currentTagID)

	if len(ret) == 0 {
		panic("no return value specified for GetPreviousTagID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, moduleID, currentTagID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, moduleID, currentTagID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, moduleID, currentTagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProtoFileContents provides a mock function with given fields: ctx, tagID
func (_m *DriftRepository) GetProtoFileContents(ctx context.Context, tagID string) (map[string]string, error) {
	ret := _m.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for GetProtoFileContents")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, tagID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, tagID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tagID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTagInfo provides a mock function with given fields: ctx, tagID
func (_m *DriftRepository) GetTagInfo(ctx context.Context, tagID string) (string, string, error) {
	ret := _m.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for GetTagInfo")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, tagID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, tagID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, tagID)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, tagID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTagsWithoutHashes provides a mock function with given fields: ctx
func (_m *DriftRepository) GetTagsWithoutHashes(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsWithoutHashes")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnacknowledgedDriftEvents provides a mock function with given fields: ctx
func (_m *DriftRepository) GetUnacknowledgedDriftEvents(ctx context.Context) ([]model.DriftEvent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnacknowledgedDriftEvents")
	}

	var r0 []model.DriftEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.DriftEvent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.DriftEvent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.DriftEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveDriftEvents provides a mock function with given fields: ctx, events
func (_m *DriftRepository) SaveDriftEvents(ctx context.Context, events []model.DriftEvent) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for SaveDriftEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.DriftEvent) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDriftRepository creates a new instance of DriftRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDriftRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DriftRepository {
	mock := &DriftRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
