version: '3.1'
services:
  db:
    image: postgres:14.7
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pbuf
      POSTGRES_PASSWORD: pbuf
      POSTGRES_DB: pbuf_registry
  pbuf-registry:
    build:
      context: .
    restart: always
    depends_on:
      - db
    ports:
    - "8080:8080"
    - "8081:8081"
    environment:
      DATA_DATABASE_DSN: "postgres://pbuf:pbuf@db:5432/pbuf_registry?sslmode=disable"
    command: >
      sh -c "/app/pbuf-migrations && /app/pbuf-registry"