version: '3.8'
services:
  db:
    image: postgres:14.7
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pbuf
      POSTGRES_PASSWORD: pbuf
      POSTGRES_DB: pbuf_registry
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "pbuf_registry" ]
      interval: 5s
      timeout: 10s
      retries: 5
  pbuf-registry:
    build:
      context: .
    restart: always
    depends_on:
      - db
    ports:
    - "8080:8080"
    - "6777:6777"
    - "8082:8082"
    healthcheck:
      test: wget -O - http://localhost:8082/healthz || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      DATA_DATABASE_DSN: "postgres://pbuf:pbuf@db:5432/pbuf_registry?sslmode=disable"
    command: >
      sh -c "/app/pbuf-migrations && /app/pbuf-registry"