name: Build and Test

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/**.md'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Test
        run: make test

      - name: Docker build
        run: make docker

  upload_proto_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pbuf cli
        id: pbuf-setup
        uses: pbufio/pbuf-setup-action@v1.0.0
        with:
          pbuf_token: ${{ secrets.PBUF_CLOUD_TOKEN }}

      - name: Install custom CA certificate
        run: |
          sudo apt-get install -y ca-certificates
          mkdir -p /usr/local/share/ca-certificates
          echo "${{ secrets.PBUF_CA_CERT }}" | sudo tee /usr/local/share/ca-certificates/pbuf.crt
          sudo update-ca-certificates

      - name: Register Module
        id: pbuf-register
        run: pbuf-cli modules register