name: Build and Test

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/**.md'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Test
        run: make test

      - name: Docker build
        run: make docker