name: Release Registry

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-wip.[0-9]+"

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Docker Login DO
        run: doctl registry login

      - name: Docker Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

      - name: Test
        run: make test

      - name: Docker Build
        env:
          REGISTRY_VERSION: ${{ github.ref_name }}
        run: make docker

      - name: Docker Push DO
        run: docker push registry.digitalocean.com/pbuf/registry:${{ github.ref_name }}

      - name: Docker Tag GHCR
        run: docker tag registry.digitalocean.com/pbuf/registry:${{ github.ref_name }} ghcr.io/pbufio/registry:${{ github.ref_name }}

      - name: Docker Push GHCR
        run: docker push ghcr.io/pbufio/registry:${{ github.ref_name }}

  upload_proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pbuf cli
        id: pbuf-setup
        uses: pbufio/pbuf-setup-action@v1.0.0
        with:
          pbuf_token: ${{ secrets.PBUF_CLOUD_TOKEN }}

      - name: Install custom CA certificate
        run: |
          sudo apt-get install -y ca-certificates
          mkdir -p /usr/local/share/ca-certificates
          echo "${{ secrets.PBUF_CA_CERT }}" | sudo tee /usr/local/share/ca-certificates/pbuf.crt
          sudo update-ca-certificates

      - name: Register Module
        id: pbuf-register
        run: pbuf-cli modules register

      - name: Push Module Tag
        id: pbuf-push
        run: pbuf-cli modules push ${{ github.ref_name }}